FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_WHATSAPP_URL=""
ENV VITE_WHATSAPP_URL=${VITE_WHATSAPP_URL}
ARG VITE_INSTAGRAM_URL=""
ENV VITE_INSTAGRAM_URL=${VITE_INSTAGRAM_URL}
ARG VITE_FACEBOOK_URL=""
ENV VITE_FACEBOOK_URL=${VITE_FACEBOOK_URL}
ARG VITE_TIKTOK_URL=""
ENV VITE_TIKTOK_URL=${VITE_TIKTOK_URL}
ARG VITE_SITE_URL="https://marecoral.com.br"
ENV VITE_SITE_URL=${VITE_SITE_URL}
ARG CATALOG_SITE_URL="https://marecoral.com.br"
ENV CATALOG_SITE_URL=${CATALOG_SITE_URL}
ARG VITE_MOSTRUARIO_API_URL="/api/v1"
ENV VITE_MOSTRUARIO_API_URL=${VITE_MOSTRUARIO_API_URL}
ARG VITE_MOSTRUARIO_TENANT="mare-coral"
ENV VITE_MOSTRUARIO_TENANT=${VITE_MOSTRUARIO_TENANT}
ARG VITE_MOSTRUARIO_CATALOG_TOKEN=""
ENV VITE_MOSTRUARIO_CATALOG_TOKEN=${VITE_MOSTRUARIO_CATALOG_TOKEN}
ARG VITE_CHECKOUT_ENABLED="false"
ENV VITE_CHECKOUT_ENABLED=${VITE_CHECKOUT_ENABLED}

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1/healthz || exit 1

CMD ["nginx", "-g", "daemon off;"]
